### ISSUE TITLE
Game crashing when placing a Computercraft Turtle

### ISSUE THREAD

**Issue by RyouhGrim** [bigrice1018/AnotherWayToSurvivalServer#2]
Loving your modpack so far, lots of mods I love in it, but when I told myself "hey myself, you should get a turtle quarry", I crafted the turtle, and when I placed it, game crashed. I created a new map, gave me a turtle, placed it, and crashed. Tried it in creative, and same result.

Here's the [report](https://pastebin.com/E0XjU2Bu) .

**Comment by bigrice1018** [comment]
Glad you like it

I'll try to find a solution for u as soon as possible tmr. It is already 12 in my timezone and i need to get some sleep...

**Comment by RyouhGrim** [comment]
Oh, thanks so much for answering then, I didn't hope anything for at least a week !
Get some good sleep, and let me know if I can help on anything.

**Comment by bigrice1018** [comment]
So when i take a look at the crash report, i find some interesting message
Are you wearing avaritia armor?

**Comment by RyouhGrim** [comment]
Nope, I'm quite early game, I was trying to get a turtle to get enough Iron to do stuff, so I'm quite far from having began avaritia.

And as I told, I created two other maps, in survival and in creative just to place down the turtles, and the game crashed. Just to test things out I created another survival map, and as long as I dont use turtles, there is no problem so far.

**Comment by bigrice1018** [comment]
Can you send me the crash report in the survival world...
Cause the report you send me is about avaritia...

**Comment by RyouhGrim** [comment]
[Here's](https://pastebin.com/hmpDMnKE) another ont that should aim the right error.
I dunno why I had an avaritia error, I'm not far enough on any of my games to do avaritia :|
(gonna have to go, exams and stuff, 'ill be back in 3-4 hours)

**Comment by bigrice1018** [comment]
I am also updating the pack and trying to solve other bugs i find
And i need to beta test the pack before releasing it
I hope i can update it tmr

**Comment by RyouhGrim** [comment]
If I can help you on anything, if you want testing something particular, just tell me, I'll be glad to help !

**Comment by bigrice1018** [comment]
cool:D 
I think i can't fix the crash and i just add a new mod to replace computercraft for now until it update

**Comment by RyouhGrim** [comment]
You're going for Open Computers ?
You gonna tweak it ?
Its much more lategame than computercraft :|

**Comment by bigrice1018** [comment]
OC already in the pack
I add another that is a port of computercraft

**Comment by bigrice1018** [comment]
Fixed in 0.2.1
By removing computercraft and replacing it with comutality

**Comment by bigrice1018** [comment]
I'll try to update the pack tmr as soon as possible
